local obj = {}
obj.__index = obj

activitymonitor = 'com.apple.ActivityMonitor'
bear = 'net.shinyfrog.bear'
chrome = 'com.google.Chrome'
dash = 'com.kapeli.dashdoc'
discord = 'com.hnc.Discord'
drafts = 'com.agiletortoise.Drafts-OSX'
fantastical = 'com.flexibits.fantastical'
finder = 'com.apple.finder'
githubDesktop = 'com.github.GitHubClient'
iterm = 'com.googlecode.iterm2'
keynote = 'com.apple.iWork.Keynote'
messages = 'com.apple.iChat'
mindnode = 'com.ideasoncanvas.mindnode.macos'
notion = 'notion.id'
omnifocus = 'com.omnigroup.OmniFocus3.MacAppStore'
onePassword = 'com.agilebits.onepassword7'
preview = 'com.apple.Preview'
postman = 'com.postmanlabs.mac'
sketch = 'com.bohemiancoding.sketch3'
slack = 'com.tinyspeck.slackmacgap'
spotify = 'com.spotify.client'
sublime = 'com.sublimetext.3'
sublimemerge = 'com.sublimemerge'
systempreferences = 'com.apple.systempreferences'
tableplus = 'com.tinyapp.TablePlus'
trello = 'com.fluidapp.FluidApp2.Trello'
vscode = 'com.microsoft.VSCode'

return obj
